/// Collection name → on-disk filename (mirrors `src/lib/local-json-db.ts`).
pub fn collection_file(collection: &str) -> String {
    match collection {
        "users" => "users.accounts.json".into(),
        "orgs" => "orgs.organizations.json".into(),
        "plans" => "plans.pricing.json".into(),
        "invoices" => "invoices.billing.json".into(),
        "payments" => "payments.transactions.json".into(),
        "plan_payments" => "plan_payments.collection.json".into(),
        "expenses" => "expenses.ledger.json".into(),
        "finance_settings" => "finance_settings.json".into(),
        "inventory_items" => "inventory-items.stock.json".into(),
        "pos_orders" => "pos-orders.sales.json".into(),
        "cashier_transactions" => "cashier_transactions.json".into(),
        "budgets" => "budgets.json".into(),
        "purchase_orders" => "purchase-orders.procurement.json".into(),
        "helpdesk_tickets" => "helpdesk-tickets.support.json".into(),
        "audit_logs" => "audit_logs.collection.json".into(),
        "contacts" => "contacts.crm.json".into(),
        "projects" => "projects.work.json".into(),
        "tasks" => "tasks.work.json".into(),
        "payroll_records" => "payroll_records.json".into(),
        "leave_requests" => "leave_requests.json".into(),
        "notifications" => "notifications.system.json".into(),
        "usage_logs" => "usage-logs.telemetry.json".into(),
        "assets" => "assets.registry.json".into(),
        "knowledge_base" => "knowledge_base.collection.json".into(),
        "user_requests" => "user_requests.collection.json".into(),
        "stock_movements" => "stock_movements.json".into(),
        "join_requests" => "join_requests.json".into(),
        "suppliers" => "suppliers.json".into(),
        "menu_categories" => "menu_categories.collection.json".into(),
        "menu_items" => "menu_items.collection.json".into(),
        "school_students" => "school_students.json".into(),
        "school_classes" => "school_classes.json".into(),
        "school_settings" => "school_settings.json".into(),
        "company_projects" => "company_projects.json".into(),
        "company_files" => "company_files.json".into(),
        "company_file_versions" => "company_file_versions.json".into(),
        "currencies" => "currencies.json".into(),
        "chart_of_accounts" => "chart_of_accounts.json".into(),
        "journal_entries" => "journal_entries.json".into(),
        "accounting_settings" => "accounting_settings.json".into(),
        other => format!("{other}.collection.json"),
    }
}

pub fn known_collections() -> &'static [&'static str] {
    &[
        "users",
        "orgs",
        "plans",
        "invoices",
        "payments",
        "plan_payments",
        "expenses",
        "finance_settings",
        "inventory_items",
        "pos_orders",
        "cashier_transactions",
        "budgets",
        "purchase_orders",
        "helpdesk_tickets",
        "audit_logs",
        "contacts",
        "projects",
        "tasks",
        "payroll_records",
        "leave_requests",
        "notifications",
        "usage_logs",
        "assets",
        "knowledge_base",
        "user_requests",
        "stock_movements",
        "join_requests",
        "suppliers",
        "menu_categories",
        "menu_items",
        "school_students",
        "school_classes",
        "school_settings",
        "company_projects",
        "company_files",
        "company_file_versions",
        "currencies",
        "chart_of_accounts",
        "journal_entries",
        "accounting_settings",
    ]
}

pub fn crypto_context(db_name: &str, file_name: &str) -> String {
    format!("{db_name}:{file_name}")
}
