mod accounting;
mod admin;
mod assets;
mod audit;
mod auth;
mod commands;
mod db;
mod finance;
mod fiscal;
mod helpdesk;
mod inventory;
mod knowledge_base;
mod licensing;
mod orgs;
mod plans;
mod pos;
mod school;
mod state;
mod store_util;
mod users;
mod join_requests;
mod payments;
mod crm;
mod payroll;
mod purchase_orders;
mod analytics;
mod projects;
mod receipt;
mod overrides;
mod currencies;
mod user_profile;
mod user_requests;

use tauri::Manager;
use tauri_plugin_store::Builder as StoreBuilder;

use auth::SessionState;
use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(StoreBuilder::default().build())
        .invoke_handler(tauri::generate_handler![
            commands::health_check,
            commands::get_app_paths,
            commands::list_db_collections,
            commands::read_collection,
            commands::write_collection,
            commands::admin::admin_load_panel_cmd,
            commands::admin::admin_update_org_cmd,
            commands::admin::admin_update_org_plan_cmd,
            commands::admin::admin_approve_join_request_cmd,
            commands::admin::admin_reject_join_request_cmd,
            commands::admin::admin_update_user_modules_cmd,
            commands::admin::admin_list_local_users_cmd,
            commands::admin::admin_list_local_companies_cmd,
            commands::admin::admin_delete_local_user_cmd,
            commands::admin::admin_delete_local_company_cmd,
            commands::analytics::analytics_get_finance_analytics_cmd,
            commands::analytics::analytics_get_hr_analytics_cmd,
            commands::analytics::analytics_get_marketing_analytics_cmd,
            commands::analytics::analytics_get_overview_analytics_cmd,
            commands::analytics::analytics_get_inventory_and_pos_analytics_cmd,
            commands::analytics::analytics_get_reports_page_data_cmd,
            commands::assets::assets_create_asset_cmd,
            commands::assets::assets_get_asset_cmd,
            commands::assets::assets_get_assets_by_org_cmd,
            commands::assets::assets_get_assets_for_current_org_cmd,
            commands::assets::assets_get_assets_by_status_cmd,
            commands::assets::assets_get_assets_by_user_cmd,
            commands::assets::assets_get_asset_by_tag_cmd,
            commands::assets::assets_update_asset_cmd,
            commands::assets::assets_assign_asset_to_user_cmd,
            commands::assets::assets_delete_asset_cmd,
            commands::audit::audit_create_audit_log_cmd,
            commands::audit::audit_get_audit_log_cmd,
            commands::audit::audit_get_audit_logs_by_org_cmd,
            commands::audit::audit_get_audit_logs_by_actor_cmd,
            commands::audit::audit_get_audit_logs_by_resource_cmd,
            commands::audit::audit_get_audit_logs_by_action_cmd,
            commands::audit::audit_get_audit_logs_by_date_range_cmd,
            commands::audit::audit_delete_old_audit_logs_cmd,
            commands::auth::auth_login,
            commands::auth::auth_logout,
            commands::auth::auth_get_current_user,
            commands::auth::auth_list_public_profiles,
            commands::auth::auth_has_users,
            commands::auth::auth_register_owner,
            commands::auth::auth_register_join,
            commands::auth::auth_list_companies,
            commands::auth::auth_list_offline_users,
            commands::auth::auth_delete_offline_user,
            commands::crm::crm_create_contact_cmd,
            commands::crm::crm_get_contact_cmd,
            commands::crm::crm_get_contacts_by_org_cmd,
            commands::crm::crm_get_contacts_for_current_org_cmd,
            commands::crm::crm_search_contacts_cmd,
            commands::crm::crm_update_contact_cmd,
            commands::crm::crm_add_deal_to_contact_cmd,
            commands::crm::crm_update_deal_on_contact_cmd,
            commands::crm::crm_delete_deal_from_contact_cmd,
            commands::crm::crm_delete_contact_cmd,
            commands::currencies::currencies_create_currency_cmd,
            commands::currencies::currencies_get_currency_by_code_cmd,
            commands::currencies::currencies_get_currency_cmd,
            commands::currencies::currencies_get_all_currencies_cmd,
            commands::currencies::currencies_get_usd_exchange_rates_cmd,
            commands::currencies::currencies_update_currency_cmd,
            commands::currencies::currencies_update_exchange_rates_cmd,
            commands::currencies::currencies_convert_currency_cmd,
            commands::currencies::currencies_delete_currency_cmd,
            commands::fiscal::fiscal_get_settings_cmd,
            commands::fiscal::fiscal_update_settings_cmd,
            commands::fiscal::fiscal_sync_config_cmd,
            commands::fiscal::fiscal_verify_taxpayer_cmd,
            commands::fiscal::fiscal_ping_device_cmd,
            commands::fiscal::fiscal_refresh_status_cmd,
            commands::fiscal::fiscal_open_day_cmd,
            commands::fiscal::fiscal_close_day_cmd,
            commands::fiscal::fiscal_register_device_cmd,
            commands::fiscal::fiscal_fiscalise_sale_cmd,
            commands::fiscal::fiscal_fiscalise_credit_note_cmd,
            commands::finance::finance_create_invoice_cmd,
            commands::finance::finance_get_invoice_cmd,
            commands::finance::finance_get_invoices_by_org_cmd,
            commands::finance::finance_update_invoice_cmd,
            commands::finance::finance_delete_invoice_cmd,
            commands::finance::finance_create_payment_cmd,
            commands::finance::finance_get_payments_by_invoice_cmd,
            commands::finance::finance_get_payments_by_org_cmd,
            commands::finance::finance_update_payment_cmd,
            commands::finance::finance_create_expense_cmd,
            commands::finance::finance_get_expenses_by_org_cmd,
            commands::finance::finance_get_expenses_by_status_cmd,
            commands::finance::finance_update_expense_cmd,
            commands::finance::finance_delete_expense_cmd,
            commands::finance::finance_get_finance_settings_cmd,
            commands::finance::finance_update_finance_settings_cmd,
            commands::finance::finance_create_cashier_transaction_cmd,
            commands::finance::finance_get_cashier_transactions_cmd,
            commands::finance::finance_get_cashier_transactions_filtered_cmd,
            commands::finance::finance_get_daily_cash_summary_cmd,
            commands::finance::finance_create_budget_cmd,
            commands::finance::finance_get_budgets_by_org_cmd,
            commands::finance::finance_update_budget_cmd,
            commands::finance::finance_delete_budget_cmd,
            commands::finance::finance_update_budget_status_cmd,
            commands::finance::finance_get_budget_variance_cmd,
            commands::finance::finance_get_budget_analytics_cmd,
            commands::finance::finance_get_financial_summary_cmd,
            commands::finance::finance_get_finance_monthly_trends_cmd,
            commands::accounting::accounting_get_settings_cmd,
            commands::accounting::accounting_update_settings_cmd,
            commands::accounting::accounting_get_chart_of_accounts_cmd,
            commands::accounting::accounting_get_journal_entries_cmd,
            commands::accounting::accounting_get_trial_balance_cmd,
            commands::accounting::accounting_get_statements_cmd,
            commands::accounting::accounting_backfill_cmd,
            commands::accounting::accounting_reconcile_cmd,
            commands::helpdesk::helpdesk_create_ticket_cmd,
            commands::helpdesk::helpdesk_get_ticket_cmd,
            commands::helpdesk::helpdesk_get_tickets_by_org_cmd,
            commands::helpdesk::helpdesk_get_tickets_for_current_org_cmd,
            commands::helpdesk::helpdesk_get_tickets_by_status_cmd,
            commands::helpdesk::helpdesk_get_tickets_by_assigned_cmd,
            commands::helpdesk::helpdesk_get_tickets_by_creator_cmd,
            commands::helpdesk::helpdesk_update_ticket_cmd,
            commands::helpdesk::helpdesk_add_message_to_ticket_cmd,
            commands::helpdesk::helpdesk_assign_ticket_cmd,
            commands::helpdesk::helpdesk_delete_ticket_cmd,
            commands::inventory::inventory_create_item_cmd,
            commands::inventory::inventory_get_all_items_cmd,
            commands::inventory::inventory_update_item_cmd,
            commands::inventory::inventory_delete_item_cmd,
            commands::inventory::inventory_bulk_upsert_items_cmd,
            commands::inventory::inventory_create_stock_movement_cmd,
            commands::inventory::inventory_get_stock_movements_cmd,
            commands::inventory::inventory_delete_stock_movement_cmd,
            commands::inventory::inventory_create_supplier_cmd,
            commands::inventory::inventory_get_all_suppliers_cmd,
            commands::inventory::inventory_update_supplier_cmd,
            commands::inventory::inventory_delete_supplier_cmd,
            commands::inventory::inventory_bulk_upsert_suppliers_cmd,
            commands::join_requests::join_requests_create_cmd,
            commands::join_requests::join_requests_get_for_current_org_cmd,
            commands::join_requests::join_requests_import_offline_cmd,
            commands::join_requests::join_requests_approve_cmd,
            commands::join_requests::join_requests_reject_cmd,
            commands::knowledge_base::knowledge_base_create_article_cmd,
            commands::knowledge_base::knowledge_base_get_article_cmd,
            commands::knowledge_base::knowledge_base_get_articles_by_org_cmd,
            commands::knowledge_base::knowledge_base_get_articles_by_category_cmd,
            commands::knowledge_base::knowledge_base_search_articles_cmd,
            commands::knowledge_base::knowledge_base_update_article_cmd,
            commands::knowledge_base::knowledge_base_delete_article_cmd,
            commands::licensing::license_get_status_cmd,
            commands::licensing::license_get_status_for_current_user_cmd,
            commands::licensing::license_sync_from_server_cmd,
            commands::licensing::license_refresh_from_remote_cmd,
            commands::licensing::license_extend_cmd,
            commands::licensing::license_has_module_access_cmd,
            commands::licensing::license_renewal_get_options_cmd,
            commands::licensing::license_renewal_peek_cmd,
            commands::licensing::license_renewal_register_cmd,
            commands::licensing::license_renewal_pay_cmd,
            commands::licensing::license_renewal_poll_status_cmd,
            commands::orgs::org_create_cmd,
            commands::orgs::org_get_cmd,
            commands::orgs::org_search_cmd,
            commands::orgs::org_sync_local_cmd,
            commands::overrides::overrides_ensure_project_cmd,
            commands::overrides::overrides_list_files_cmd,
            commands::overrides::overrides_get_file_cmd,
            commands::overrides::overrides_upsert_file_cmd,
            commands::overrides::overrides_delete_file_cmd,
            commands::overrides::overrides_resolve_or_default_cmd,
            commands::overrides::overrides_run_shell_command_cmd,
            commands::payments::payments_get_for_org_cmd,
            commands::payments::payments_get_for_current_org_cmd,
            commands::payments::payments_initiate_plan_payment_cmd,
            commands::payments::payments_check_plan_payment_status_cmd,
            commands::payments::payments_initiate_pos_paynow_payment_cmd,
            commands::payroll::payroll_get_org_members_for_hr_cmd,
            commands::payroll::payroll_create_record_cmd,
            commands::payroll::payroll_get_record_cmd,
            commands::payroll::payroll_get_records_by_org_cmd,
            commands::payroll::payroll_get_records_for_current_org_cmd,
            commands::payroll::payroll_get_records_by_employee_cmd,
            commands::payroll::payroll_get_records_by_period_cmd,
            commands::payroll::payroll_update_record_cmd,
            commands::payroll::payroll_delete_record_cmd,
            commands::payroll::payroll_create_leave_request_cmd,
            commands::payroll::payroll_get_leave_request_cmd,
            commands::payroll::payroll_get_leave_requests_by_org_cmd,
            commands::payroll::payroll_get_leave_requests_for_current_org_cmd,
            commands::payroll::payroll_get_leave_requests_by_employee_cmd,
            commands::payroll::payroll_get_leave_requests_by_status_cmd,
            commands::payroll::payroll_update_leave_request_cmd,
            commands::payroll::payroll_delete_leave_request_cmd,
            commands::plans::plan_get_cmd,
            commands::plans::plan_get_by_slug_cmd,
            commands::plans::plan_get_all_cmd,
            commands::pos::pos_create_order_cmd,
            commands::pos::pos_complete_order_cmd,
            commands::pos::pos_get_orders_cmd,
            commands::pos::pos_get_register_activity_cmd,
            commands::pos::pos_get_menu_categories_cmd,
            commands::pos::pos_get_menu_items_cmd,
            commands::pos::pos_sync_inventory_to_pos_cmd,
            commands::pos::pos_get_inventory_items_for_pos_cmd,
            commands::projects::projects_get_org_members_for_tasks_cmd,
            commands::projects::projects_create_project_cmd,
            commands::projects::projects_get_project_cmd,
            commands::projects::projects_get_projects_by_org_cmd,
            commands::projects::projects_get_projects_for_current_org_cmd,
            commands::projects::projects_get_projects_by_status_cmd,
            commands::projects::projects_update_project_cmd,
            commands::projects::projects_add_member_to_project_cmd,
            commands::projects::projects_delete_project_cmd,
            commands::projects::projects_create_task_cmd,
            commands::projects::projects_get_task_cmd,
            commands::projects::projects_get_tasks_by_project_cmd,
            commands::projects::projects_get_tasks_by_org_cmd,
            commands::projects::projects_get_tasks_for_current_org_cmd,
            commands::projects::projects_get_tasks_by_assigned_cmd,
            commands::projects::projects_get_tasks_by_status_cmd,
            commands::projects::projects_update_task_cmd,
            commands::projects::projects_delete_task_cmd,
            commands::projects::projects_get_work_board_config_cmd,
            commands::projects::projects_save_work_board_config_cmd,
            commands::projects::projects_migrate_task_statuses_cmd,
            commands::projects::projects_migrate_project_statuses_cmd,
            commands::purchase_orders::purchase_orders_create_cmd,
            commands::purchase_orders::purchase_orders_get_cmd,
            commands::purchase_orders::purchase_orders_get_by_org_cmd,
            commands::purchase_orders::purchase_orders_get_for_current_org_cmd,
            commands::purchase_orders::purchase_orders_get_by_status_cmd,
            commands::purchase_orders::purchase_orders_get_by_vendor_cmd,
            commands::purchase_orders::purchase_orders_update_cmd,
            commands::purchase_orders::purchase_orders_approve_cmd,
            commands::purchase_orders::purchase_orders_delete_cmd,
            commands::receipt::receipt_get_design_for_current_org_cmd,
            commands::receipt::receipt_update_design_for_current_org_cmd,
            commands::school::school_get_settings_cmd,
            commands::school::school_update_settings_cmd,
            commands::school::school_get_classes_cmd,
            commands::school::school_create_class_cmd,
            commands::school::school_update_class_cmd,
            commands::school::school_delete_class_cmd,
            commands::school::school_get_students_cmd,
            commands::school::school_get_student_cmd,
            commands::school::school_create_student_cmd,
            commands::school::school_update_student_cmd,
            commands::school::school_delete_student_cmd,
            commands::school::school_build_fee_snapshot_cmd,
            commands::school::school_get_student_term_fee_balance_cmd,
            commands::school::school_get_receipt_fee_info_cmd,
            commands::school::school_get_students_with_balances_cmd,
            commands::school::school_create_classes_from_templates_cmd,
            commands::school::school_get_dashboard_stats_cmd,
            commands::user_profile::user_profile_get_current_cmd,
            commands::user_profile::user_profile_update_current_cmd,
            commands::user_profile::user_profile_get_display_name_cmd,
            commands::user_requests::user_requests_create_user_request_cmd,
            commands::user_requests::user_requests_get_user_request_cmd,
            commands::user_requests::user_requests_get_user_requests_by_org_cmd,
            commands::user_requests::user_requests_get_user_requests_for_current_org_cmd,
            commands::user_requests::user_requests_get_user_requests_by_user_cmd,
            commands::user_requests::user_requests_get_user_requests_by_status_cmd,
            commands::user_requests::user_requests_update_user_request_cmd,
            commands::user_requests::user_requests_delete_user_request_cmd,
            commands::users::users_get_members_cmd,
            commands::users::users_update_allowed_modules_cmd,
        ])
        .setup(|app| {
            let app_state = AppState::from_app(app)?;
            let session_state = SessionState::new();
            session_state.restore(&app_state.secrets_dir());
            app.manage(app_state);
            app.manage(session_state);
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building tauri application")
        .run(|_app_handle, _event| {});
}
